create table if not exists public.plant_readings (
  id bigint generated by default as identity primary key,
  ts timestamptz not null,
  temperature_c double precision,
  humidity_percent double precision,
  soil_moisture_raw integer,
  soil_moisture_percent double precision,
  light_raw integer,
  light_lux double precision,
  needs_water boolean
);

create index if not exists plant_readings_ts_idx on public.plant_readings (ts desc);

alter table public.plant_readings enable row level security;

drop policy if exists "allow anon insert plant readings" on public.plant_readings;
create policy "allow anon insert plant readings"
  on public.plant_readings
  for insert
  to anon
  with check (true);

drop policy if exists "allow anon read plant readings" on public.plant_readings;
create policy "allow anon read plant readings"
  on public.plant_readings
  for select
  to anon
  using (true);
